// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: services.proto

package gateway

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for weather conditions
type WeatherCondition int32

const (
	WeatherCondition_SUNNY  WeatherCondition = 0
	WeatherCondition_CLOUDY WeatherCondition = 1
	WeatherCondition_RAINY  WeatherCondition = 2
	WeatherCondition_STORMY WeatherCondition = 3
)

// Enum value maps for WeatherCondition.
var (
	WeatherCondition_name = map[int32]string{
		0: "SUNNY",
		1: "CLOUDY",
		2: "RAINY",
		3: "STORMY",
	}
	WeatherCondition_value = map[string]int32{
		"SUNNY":  0,
		"CLOUDY": 1,
		"RAINY":  2,
		"STORMY": 3,
	}
)

func (x WeatherCondition) Enum() *WeatherCondition {
	p := new(WeatherCondition)
	*p = x
	return p
}

func (x WeatherCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeatherCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_services_proto_enumTypes[0].Descriptor()
}

func (WeatherCondition) Type() protoreflect.EnumType {
	return &file_services_proto_enumTypes[0]
}

func (x WeatherCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeatherCondition.Descriptor instead.
func (WeatherCondition) EnumDescriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings.
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message for weather, containing the city.
type WeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *WeatherRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// The response message for weather.
type WeatherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"` // in Celsius
	Humidity      int32                  `protobuf:"varint,2,opt,name=humidity,proto3" json:"humidity,omitempty"`        // in percentage
	Condition     WeatherCondition       `protobuf:"varint,3,opt,name=condition,proto3,enum=rpc_tutorial.WeatherCondition" json:"condition,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherReply) Reset() {
	*x = WeatherReply{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherReply) ProtoMessage() {}

func (x *WeatherReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherReply.ProtoReflect.Descriptor instead.
func (*WeatherReply) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *WeatherReply) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherReply) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherReply) GetCondition() WeatherCondition {
	if x != nil {
		return x.Condition
	}
	return WeatherCondition_SUNNY
}

func (x *WeatherReply) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\frpc_tutorial\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x0eWeatherRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"\xac\x01\n" +
	"\fWeatherReply\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x05R\bhumidity\x12<\n" +
	"\tcondition\x18\x03 \x01(\x0e2\x1e.rpc_tutorial.WeatherConditionR\tcondition\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription*@\n" +
	"\x10WeatherCondition\x12\t\n" +
	"\x05SUNNY\x10\x00\x12\n" +
	"\n" +
	"\x06CLOUDY\x10\x01\x12\t\n" +
	"\x05RAINY\x10\x02\x12\n" +
	"\n" +
	"\x06STORMY\x10\x032\xa7\x02\n" +
	"\aGreeter\x12b\n" +
	"\bSayHello\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/greeter/say_hello\x12H\n" +
	"\x0eSayHelloStream\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply0\x01\x12n\n" +
	"\x0eAggregateHello\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/greeter/aggregate_hello2m\n" +
	"\aWeather\x12b\n" +
	"\n" +
	"GetWeather\x12\x1c.rpc_tutorial.WeatherRequest\x1a\x1a.rpc_tutorial.WeatherReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/weather/{city}BB\n" +
	"\x19com.example.grpc.servicesB\rServicesProtoP\x01Z\x14rpc-tutorial/gatewayb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_proto_goTypes = []any{
	(WeatherCondition)(0),  // 0: rpc_tutorial.WeatherCondition
	(*HelloRequest)(nil),   // 1: rpc_tutorial.HelloRequest
	(*HelloReply)(nil),     // 2: rpc_tutorial.HelloReply
	(*WeatherRequest)(nil), // 3: rpc_tutorial.WeatherRequest
	(*WeatherReply)(nil),   // 4: rpc_tutorial.WeatherReply
}
var file_services_proto_depIdxs = []int32{
	0, // 0: rpc_tutorial.WeatherReply.condition:type_name -> rpc_tutorial.WeatherCondition
	1, // 1: rpc_tutorial.Greeter.SayHello:input_type -> rpc_tutorial.HelloRequest
	1, // 2: rpc_tutorial.Greeter.SayHelloStream:input_type -> rpc_tutorial.HelloRequest
	1, // 3: rpc_tutorial.Greeter.AggregateHello:input_type -> rpc_tutorial.HelloRequest
	3, // 4: rpc_tutorial.Weather.GetWeather:input_type -> rpc_tutorial.WeatherRequest
	2, // 5: rpc_tutorial.Greeter.SayHello:output_type -> rpc_tutorial.HelloReply
	2, // 6: rpc_tutorial.Greeter.SayHelloStream:output_type -> rpc_tutorial.HelloReply
	2, // 7: rpc_tutorial.Greeter.AggregateHello:output_type -> rpc_tutorial.HelloReply
	4, // 8: rpc_tutorial.Weather.GetWeather:output_type -> rpc_tutorial.WeatherReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		EnumInfos:         file_services_proto_enumTypes,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
