# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """The greeter service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/rpc_tutorial.Greeter/SayHello',
                request_serializer=services__pb2.HelloRequest.SerializeToString,
                response_deserializer=services__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SayHelloStream = channel.unary_stream(
                '/rpc_tutorial.Greeter/SayHelloStream',
                request_serializer=services__pb2.HelloRequest.SerializeToString,
                response_deserializer=services__pb2.HelloReply.FromString,
                _registered_method=True)
        self.AggregateHello = channel.unary_unary(
                '/rpc_tutorial.Greeter/AggregateHello',
                request_serializer=services__pb2.HelloRequest.SerializeToString,
                response_deserializer=services__pb2.HelloReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeter service definition.
    """

    def SayHello(self, request, context):
        """Unary call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloStream(self, request, context):
        """Server-streaming call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateHello(self, request, context):
        """Unary call for backend-to-backend communication demonstration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=services__pb2.HelloRequest.FromString,
                    response_serializer=services__pb2.HelloReply.SerializeToString,
            ),
            'SayHelloStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHelloStream,
                    request_deserializer=services__pb2.HelloRequest.FromString,
                    response_serializer=services__pb2.HelloReply.SerializeToString,
            ),
            'AggregateHello': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateHello,
                    request_deserializer=services__pb2.HelloRequest.FromString,
                    response_serializer=services__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_tutorial.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_tutorial.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeter service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_tutorial.Greeter/SayHello',
            services__pb2.HelloRequest.SerializeToString,
            services__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SayHelloStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rpc_tutorial.Greeter/SayHelloStream',
            services__pb2.HelloRequest.SerializeToString,
            services__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_tutorial.Greeter/AggregateHello',
            services__pb2.HelloRequest.SerializeToString,
            services__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WeatherStub(object):
    """The weather service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeather = channel.unary_unary(
                '/rpc_tutorial.Weather/GetWeather',
                request_serializer=services__pb2.WeatherRequest.SerializeToString,
                response_deserializer=services__pb2.WeatherReply.FromString,
                _registered_method=True)


class WeatherServicer(object):
    """The weather service definition
    """

    def GetWeather(self, request, context):
        """Unary call to get weather information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeather,
                    request_deserializer=services__pb2.WeatherRequest.FromString,
                    response_serializer=services__pb2.WeatherReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_tutorial.Weather', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_tutorial.Weather', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Weather(object):
    """The weather service definition
    """

    @staticmethod
    def GetWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_tutorial.Weather/GetWeather',
            services__pb2.WeatherRequest.SerializeToString,
            services__pb2.WeatherReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
