# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0crpc_tutorial\x1a\x1cgoogle/api/annotations.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"}\n\x0cWeatherReply\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x05\x12\x31\n\tcondition\x18\x03 \x01(\x0e\x32\x1e.rpc_tutorial.WeatherCondition\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t*@\n\x10WeatherCondition\x12\t\n\x05SUNNY\x10\x00\x12\n\n\x06\x43LOUDY\x10\x01\x12\t\n\x05RAINY\x10\x02\x12\n\n\x06STORMY\x10\x03\x32\xa7\x02\n\x07Greeter\x12\x62\n\x08SayHello\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply\" \x82\xd3\xe4\x93\x02\x1a\"\x15/v1/greeter/say_hello:\x01*\x12H\n\x0eSayHelloStream\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply0\x01\x12n\n\x0e\x41ggregateHello\x12\x1a.rpc_tutorial.HelloRequest\x1a\x18.rpc_tutorial.HelloReply\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/greeter/aggregate_hello:\x01*2m\n\x07Weather\x12\x62\n\nGetWeather\x12\x1c.rpc_tutorial.WeatherRequest\x1a\x1a.rpc_tutorial.WeatherReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/weather/{city}BB\n\x19\x63om.example.grpc.servicesB\rServicesProtoP\x01Z\x14rpc-tutorial/gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.example.grpc.servicesB\rServicesProtoP\001Z\024rpc-tutorial/gateway'
  _globals['_GREETER'].methods_by_name['SayHello']._loaded_options = None
  _globals['_GREETER'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\032\"\025/v1/greeter/say_hello:\001*'
  _globals['_GREETER'].methods_by_name['AggregateHello']._loaded_options = None
  _globals['_GREETER'].methods_by_name['AggregateHello']._serialized_options = b'\202\323\344\223\002 \"\033/v1/greeter/aggregate_hello:\001*'
  _globals['_WEATHER'].methods_by_name['GetWeather']._loaded_options = None
  _globals['_WEATHER'].methods_by_name['GetWeather']._serialized_options = b'\202\323\344\223\002\024\022\022/v1/weather/{city}'
  _globals['_WEATHERCONDITION']._serialized_start=282
  _globals['_WEATHERCONDITION']._serialized_end=346
  _globals['_HELLOREQUEST']._serialized_start=62
  _globals['_HELLOREQUEST']._serialized_end=90
  _globals['_HELLOREPLY']._serialized_start=92
  _globals['_HELLOREPLY']._serialized_end=121
  _globals['_WEATHERREQUEST']._serialized_start=123
  _globals['_WEATHERREQUEST']._serialized_end=153
  _globals['_WEATHERREPLY']._serialized_start=155
  _globals['_WEATHERREPLY']._serialized_end=280
  _globals['_GREETER']._serialized_start=349
  _globals['_GREETER']._serialized_end=644
  _globals['_WEATHER']._serialized_start=646
  _globals['_WEATHER']._serialized_end=755
# @@protoc_insertion_point(module_scope)
